<?php

namespace AppBundle\Repository;

/**
 * MaquinaUbicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaquinaUbicacionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Insert a ubication for a machine
     * @param $machine
     * @return array
     */
    public function insertMachineUbication($machine, $ubication, $user, $location = []){

        $conn = $this->getEntityManager()->getConnection();

        $query = "INSERT INTO 
                maquina_ubicacion 
                    (
                    id_maquina, 
                    id_ubicacion, 
                    id_usuario,
                    created,
                    latitud,
                    longitud
                ) 
                VALUES (?, ?, ?, NOW(), ?, ?)";

        $stmt = $conn->prepare($query);
        $stmt->bindValue(1, $machine->getId());
        $stmt->bindValue(2, $ubication->getId());
        $stmt->bindValue(3, $user->getId());
        $stmt->bindValue(4, $location['latitude']);
        $stmt->bindValue(5, $location['longitude']);
        $stmt->execute();
    }
}
