<?php

namespace AppBundle\Repository;

/**
 * MaquinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaquinaRepository extends \Doctrine\ORM\EntityRepository
{
}
